const data = {
  carCopy: [
    {
      id: 1,
      title: "Tata Nexon",
      price: 50000,
      category: "Compact SUV",
      image: "...",
      color: "white",
      condition: "New",
      buildYear: "2020",
      make: "TATA",
      model: "XE",
    },
    /*...*/
    {
      id: 2,
      title: "Kia Sonet",
      price: 225000,
      category: "Compact SUV",
      image: "...",
      color: "black",
      condition: "new",
      buildYear: "2020",
      make: "Kia",
      model: "1.2 HTE 5MT",
    },
    {
      id: 3,
      title: "Ford EcoSport",
      price: 300000,
      category: "Compact SUV",
      image: "...",
      color: "blue",
      condition: "new",
      buildYear: "2020",
      make: "Ford",
      model: "1.5L Petrol Ambiente MT",
    },
    {
      id: 4,
      title: "Hyundai Venue",
      price: 1675000,
      category: "Compact SUV",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 5,
      title: "Hyundai Venue",
      price: 875000,
      category: "Compact SUV",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 6,
      title: "Hyundai Venue",
      price: 500000,
      category: "Compact SUV",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 7,
      title: "Hyundai Venue",
      price: 2575000,
      category: "Compact SUV",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 8,
      title: "Hyundai Venue",
      price: 600000,
      category: "Compact SUV",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 9,
      title: "Hyundai Venue",
      price: 150000,
      category: "Compact SUV",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 10,
      title: "Hyundai Venue",
      price: 480000,
      category: "Compact SUV",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 11,
      title: "Hyundai Venue",
      price: 955000,
      category: "Compact SUV",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 12,
      title: "Hyundai Venue",
      price: 740000,
      category: "Compact SUV",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 13,
      title: "Hyundai Venue",
      price: 520000,
      category: "Premium hatchback",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 15,
      title: "Hyundai Venue",
      price: 98000,
      category: "Premium hatchback",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 16,
      title: "Hyundai Venue",
      price: 375000,
      category: "Hatchback",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 17,
      title: "Hyundai Venue",
      price: 347000,
      category: "Hatchback",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 18,
      title: "Hyundai Venue",
      price: 552000,
      category: "Hatchback",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 19,
      title: "Hyundai Venue",
      price: 614000,
      category: "Hatchback",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 20,
      title: "Hyundai Venue",
      price: 1005000,
      category: "Hatchback",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
    {
      id: 21,
      title: "Hyundai Venue",
      price: 75000,
      category: "Hatchback",
      image: "...",
      color: "grey",
      condition: "new",
      buildYear: "2020",
      make: "Hyundai",
      model: "1.2 Kappa MT E",
    },
  ],
  categories: [
    {
      id: 0,
      title: "",
    },
    {
      id: 1,
      title: "Compact SUV",
    },
    {
      id: 2,
      title: "Premium hatchback",
    },
    {
      id: 3,
      title: "Hatchback",
    },
  ],
  condition: [
    {
      id: 0,
      title: "",
    },
    {
      id: 1,
      type: "used",
    },
    {
      id: 2,
      type: "damaged",
    },
  ],
  makes: [
    {
      id: 0,
      title: "",
    },
    {
      id: 1,
      name: "TATA",
    },
    {
      id: 2,
      name: "Kia",
    },
    {
      id: 3,
      name: "Hyundai",
    },
    {
      id: 4,
      name: "Ford",
    },
    {
      id: 5,
      name: "Maruti",
    },
  ],
};

export default data;
